diginote/urls.py
from django.contrib import admin
from django.urls import path, include
# from diginote.views import HomeView
from diginote.views import SignupView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include(("django.contrib.auth.urls", "accounts"), namespace='accounts')),  # login, logout, password
    path("accounts/signup", SignupView.as_view(), name="signup"),
    path("", include(("note.urls", "notes"), namespace="notes"), name="home"),
]

note/urls.py
from django.urls import path
from note.views import (
    NoteListView,
    NoteDetailView,
    NoteCreateView,
    NoteUpdateView,
    NoteDeleteView)

urlpatterns = [
    path("", NoteListView.as_view(), name="all"),
    path('<int:pk>/detail', NoteDetailView.as_view(), name='note_detail'),
    path('create', NoteCreateView.as_view(), name='note_create'),
    path('<int:pk>/update', NoteUpdateView.as_view(), name='note_update'),
    path('<int:pk>/delete', NoteDeleteView.as_view(), name='note_delete'),
]

note/models.py
from django.db import models
from django.conf import settings

class Note(models.Model):

    title = models.CharField(max_length = 200)
    body = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
 
    def __str__(self):
        return self.title

note/forms.py
from django.forms import ModelForm
from note.models import Note

class NoteCreateForm(ModelForm):

    class Meta:
        model = Note
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(NoteCreateForm, self).__init__(*args, **kwargs)

diginote/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


class SignupView(View):
    """
    Account signup view.
    """

    form_class = UserCreationForm
    template_name = 'registration/signup.html'

    def get(self, request, *args, **kwargs):
        """
        Handle GET request; render empty form.
        """
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        """
        Handle POST request.
        """
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('notes:all')
        return render(request, self.template_name, {'form': form})

note/views.py
from django.shortcuts import redirect
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from note.models import Note
from note.forms import NoteCreateForm



class NoteBaseView(View):
    """
    Base view for create, list, detail, update and delete class views.
    """
    model = Note

    # protect inheritor views from anonyous
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class SingleNoteBaseView(NoteBaseView):
    """
    Base view for detail, update, and delete class views.
    """

    def get_queryset(self):
        """
        Override the default queryset
        to protect access beside the owner.
        """
        return Note.objects.filter(id=self.kwargs["pk"], user=self.request.user)


class NoteCreateView(NoteBaseView, CreateView):
    """
    Generic detail view
    template name: note/note_form.html
    """
    form_class = NoteCreateForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect("notes:all")

    def get_form_kwargs(self, *args, **kwargs):
        """
        Override the submitted form values to add the "user" value
        """
        kwargs = super(NoteCreateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs


class NoteListView(NoteBaseView, ListView):
    """
    Generic detail view
    template name: note/note_list.html
    context variables include 'note_list' object name
    """

    def get_queryset(self):
        """
        Override the default queryset to only get notes owned by the user.
        """
        qs = Note.objects.filter(user=self.request.user)
        query = self.request.GET.get('q')
        if query:
            qs = qs.filter(title__icontains=query)
        return qs.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(NoteListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', "")
        return context


class NoteDetailView(SingleNoteBaseView, DetailView):
    """
    Generic detail view
    template name: note/note_detail.html
    context variables include 'note' object name
    query_set is defined in SingleNoteBaseView
    """

class NoteUpdateView(SingleNoteBaseView, UpdateView):
    """
    Generic update view
    template name: note/note_form.html
    context variables include 'note' object name
    """
    fields = ['title', 'body'] # fields to be updated

    def get_success_url(self, **kwargs):
        """
        Url to be redirected to when update successful.
        """
        return reverse_lazy("notes:note_detail", args=(self.kwargs["pk"],))


class NoteDeleteView(SingleNoteBaseView, DeleteView):
    """
    Generic delete view
    template: note/note_confirm_delete.html
    context variables include 'note' object name
    """
    success_url = reverse_lazy("notes:all") # redirect to on success

diginote/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title> {% block title %}{% endblock %} | Diginote</title>
</head>

<body>
    <div class="page">
        <header style="display: flex; justify-content: space-between;">
            <a href="{%url 'notes:all' %}">Diginote</a>
            {% if request.user.is_authenticated %}
            <span>Welcome <strong>{{ request.user.username }}</strong>, <a href="{% url 'accounts:logout' %}" title="Logout">Logout</a></span>
            {% endif %}
        </header>
        <hr />
        <main>
        {% block content %}{% endblock %}
        </main>
        <footer>
            <hr />
            <p>Copyright &copy; {% now "Y" %}</p>
        </footer>
    </div>
</body>
</html>

note/templates/note/note_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'notes:all' as list_all %}
<h1 class="mb-5">Delete Note</h1>

<p class="h5">Are you sure you want to delete the Note:</p>
<h3>{{ note.title }}</h3>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm" />
    <input type="submit" onclick="window.location='{{list_all}}'; return false;" value="Cancel" />
</form>

{% endblock %}

note/templates/note/note_detail.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">{{ note.title }}</h1>
<div class="body">
    {{ note.body }}
</div>
<p>&nbsp;</p>
<hr />
<div class="actions">
    <a href="{% url 'notes:all' %}">Back</a> |
    <a href="{% url 'notes:note_update' note.id %}">Edit</a> |
    <a href="{% url 'notes:note_delete' note.id %}">Delete</a>
</div>

{% endblock %}

note/templates/note/note_form.html
{% extends "base.html" %}

{% block content %}

<div class="form">
    <form action="" method="post">
        {% csrf_token %}
        <table class="table">
            {{form.as_table}}
        </table>
        <hr />
        <div class="actions">
            <input type="submit" value="Submit" />
            <input type="submit" onclick="window.location='{% url 'notes:all' %}'; return false;" value="Cancel">
        </div>
    </form>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

note/templates/note/note_list.html
{% extends 'base.html' %}
{% block title %}List{% endblock %}
{% block content %}

<div style="display: flex; justify-content: space-between;">
<h2 style="margin: 0;">Your notes</h2>
<form action={% url 'notes:all' %} method="GET">
    <input type="text" name="q" value="{{ q }}"" />
    <input type="submit" value="Search" />
    <input type="submit" onclick="window.location='{% url 'notes:all' %}'; return false;" value="Clear">
</form>
</div>
<hr />
{%if note_list|length > 0 %}
<ul>
    {% for note in note_list %}
    <li>
        <a href="{% url 'notes:note_detail' note.id %}">{{note.title}}</a>
    </li>
    {% endfor %}
</ul>
<hr />
<div class="actions">
    <a href="{% url 'notes:note_create' %}">Add another note</a>
</div>
{% else %}
{% if not q %}
<div>
    <p></p>You don't have any note.</div>
    <p><a href="{% url 'notes:note_create' %}">Create a new note</a></p>
</div>
{% else %}
<div>
    <p>There's no note found.</p>
</div>
</div>
{% endif %}
{% endif %}

{% endblock %}